#!/usr/bin/env python3
"""Generate JSON Schema enum fragments from vocab/*.json files.

The vocabulary JSON files are the human-maintained source of truth. The
generated schema fragments are used by spec/schemas/metadata-input.schema.json
for editor and CI validation.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VOCABS = {
    "domain": {
        "source": ROOT / "vocab" / "domain.json",
        "target": ROOT / "spec" / "schemas" / "vocab" / "domain.schema.json",
        "title": "CDH Domain Vocabulary",
    },
    "commodity": {
        "source": ROOT / "vocab" / "commodity.json",
        "target": ROOT / "spec" / "schemas" / "vocab" / "commodity.schema.json",
        "title": "CDH Commodity Vocabulary",
    },
    "hazard": {
        "source": ROOT / "vocab" / "hazard.json",
        "target": ROOT / "spec" / "schemas" / "vocab" / "hazard.schema.json",
        "title": "CDH Hazard Vocabulary",
    },
}


def concept_ids(path: Path) -> list[str]:
    """Extract concepts[].id values from the CDH vocab JSON shape."""
    data = json.loads(path.read_text(encoding="utf-8"))
    ids = [concept["id"] for concept in data.get("concepts", []) if "id" in concept]

    if not ids:
        raise ValueError(f"No concepts[].id values found in {path}")

    duplicates = sorted({item for item in ids if ids.count(item) > 1})
    if duplicates:
        raise ValueError(f"Duplicate concept ids in {path}: {', '.join(duplicates)}")

    return ids


def schema_for(name: str, ids: list[str], title: str) -> dict:
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": f"https://cgiar.org/cdh/schemas/vocab/{name}.schema.json",
        "title": title,
        "description": (
            f"Generated from vocab/{name}.json. Do not edit this file directly; "
            "update the JSON vocabulary and regenerate schemas."
        ),
        "type": "string",
        "enum": ids,
    }


def render(schema: dict) -> str:
    return json.dumps(schema, indent=2, ensure_ascii=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated files are not up to date.",
    )
    args = parser.parse_args()

    changed: list[Path] = []

    for name, config in VOCABS.items():
        source = config["source"]
        target = config["target"]
        output = render(schema_for(name, concept_ids(source), config["title"]))

        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != output:
                changed.append(target)
            continue

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(output, encoding="utf-8")

    if changed:
        for path in changed:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        print("Run: just schemas", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
